name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    timeout-minutes: 3

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4.1.1

      - name: Set up Node
        uses: actions/setup-node@v4.0.0
        with:
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci

      - name: Install dependencies
        run: |
          npm run test
